//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:44:22 AM CET 
//


package no.ssb.linkmobility.jaxb.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "net",
    "tariff",
    "text",
    "_class",
    "op",
    "rcpreq",
    "rcpfrm",
    "snd",
    "rcv",
    "ttl",
    "cpatag",
    "agelimit",
    "shortcode",
    "replace",
    "deliverytime",
    "servicecode"
})
@XmlRootElement(name = "MSG")
public class MSG {

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "NET")
    protected String net;
    @XmlElement(name = "TARIFF")
    protected String tariff;
    @XmlElement(name = "TEXT", required = true)
    protected String text;
    @XmlElement(name = "CLASS")
    protected String _class;
    @XmlElement(name = "OP")
    protected String op;
    @XmlElement(name = "RCPREQ")
    protected String rcpreq;
    @XmlElement(name = "RCPFRM")
    protected RCPFRM rcpfrm;
    @XmlElement(name = "SND")
    protected String snd;
    @XmlElement(name = "RCV", required = true)
    protected String rcv;
    @XmlElement(name = "TTL")
    protected String ttl;
    @XmlElement(name = "CPATAG")
    protected String cpatag;
    @XmlElement(name = "AGELIMIT")
    protected String agelimit;
    @XmlElement(name = "SHORTCODE")
    protected String shortcode;
    @XmlElement(name = "REPLACE")
    protected String replace;
    @XmlElement(name = "DELIVERYTIME")
    protected String deliverytime;
    @XmlElement(name = "SERVICECODE")
    protected String servicecode;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the net property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNET() {
        return net;
    }

    /**
     * Sets the value of the net property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNET(String value) {
        this.net = value;
    }

    /**
     * Gets the value of the tariff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTARIFF() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTARIFF(String value) {
        this.tariff = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the class property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLASS() {
        return _class;
    }

    /**
     * Sets the value of the class property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLASS(String value) {
        this._class = value;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOP() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOP(String value) {
        this.op = value;
    }

    /**
     * Gets the value of the rcpreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRCPREQ() {
        return rcpreq;
    }

    /**
     * Sets the value of the rcpreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRCPREQ(String value) {
        this.rcpreq = value;
    }

    /**
     * Gets the value of the rcpfrm property.
     * 
     * @return
     *     possible object is
     *     {@link RCPFRM }
     *     
     */
    public RCPFRM getRCPFRM() {
        return rcpfrm;
    }

    /**
     * Sets the value of the rcpfrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link RCPFRM }
     *     
     */
    public void setRCPFRM(RCPFRM value) {
        this.rcpfrm = value;
    }

    /**
     * Gets the value of the snd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSND() {
        return snd;
    }

    /**
     * Sets the value of the snd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSND(String value) {
        this.snd = value;
    }

    /**
     * Gets the value of the rcv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRCV() {
        return rcv;
    }

    /**
     * Sets the value of the rcv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRCV(String value) {
        this.rcv = value;
    }

    /**
     * Gets the value of the ttl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTL() {
        return ttl;
    }

    /**
     * Sets the value of the ttl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTL(String value) {
        this.ttl = value;
    }

    /**
     * Gets the value of the cpatag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPATAG() {
        return cpatag;
    }

    /**
     * Sets the value of the cpatag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPATAG(String value) {
        this.cpatag = value;
    }

    /**
     * Gets the value of the agelimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGELIMIT() {
        return agelimit;
    }

    /**
     * Sets the value of the agelimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGELIMIT(String value) {
        this.agelimit = value;
    }

    /**
     * Gets the value of the shortcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHORTCODE() {
        return shortcode;
    }

    /**
     * Sets the value of the shortcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHORTCODE(String value) {
        this.shortcode = value;
    }

    /**
     * Gets the value of the replace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPLACE() {
        return replace;
    }

    /**
     * Sets the value of the replace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPLACE(String value) {
        this.replace = value;
    }

    /**
     * Gets the value of the deliverytime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYTIME() {
        return deliverytime;
    }

    /**
     * Sets the value of the deliverytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYTIME(String value) {
        this.deliverytime = value;
    }

    /**
     * Gets the value of the servicecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICECODE() {
        return servicecode;
    }

    /**
     * Sets the value of the servicecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICECODE(String value) {
        this.servicecode = value;
    }

}
