//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:44:22 AM CET 
//


package no.ssb.linkmobility.jaxb.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.ssb.linkmobility package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.ssb.linkmobility
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSGLST }
     * 
     */
    public MSGLST createMSGLST() {
        return new MSGLST();
    }

    /**
     * Create an instance of {@link MSG }
     * 
     */
    public MSG createMSG() {
        return new MSG();
    }

    /**
     * Create an instance of {@link RCPFRM }
     * 
     */
    public RCPFRM createRCPFRM() {
        return new RCPFRM();
    }

    /**
     * Create an instance of {@link SESSION }
     * 
     */
    public SESSION createSESSION() {
        return new SESSION();
    }

    /**
     * Create an instance of {@link QRYLST }
     * 
     */
    public QRYLST createQRYLST() {
        return new QRYLST();
    }

    /**
     * Create an instance of {@link QRY }
     * 
     */
    public QRY createQRY() {
        return new QRY();
    }

    /**
     * Create an instance of {@link RCPFMT }
     * 
     */
    public RCPFMT createRCPFMT() {
        return new RCPFMT();
    }

}
