//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:44:22 AM CET 
//


package no.ssb.linkmobility.jaxb.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "client",
    "pw",
    "ap",
    "sd",
    "msglst",
    "qrylst"
})
@XmlRootElement(name = "SESSION")
public class SESSION {

    @XmlElement(name = "CLIENT", required = true)
    protected String client;
    @XmlElement(name = "PW", required = true)
    protected String pw;
    @XmlElement(name = "AP")
    protected String ap;
    @XmlElement(name = "SD")
    protected String sd;
    @XmlElement(name = "MSGLST")
    protected MSGLST msglst;
    @XmlElement(name = "QRYLST")
    protected QRYLST qrylst;

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLIENT() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLIENT(String value) {
        this.client = value;
    }

    /**
     * Gets the value of the pw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPW() {
        return pw;
    }

    /**
     * Sets the value of the pw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPW(String value) {
        this.pw = value;
    }

    /**
     * Gets the value of the ap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAP() {
        return ap;
    }

    /**
     * Sets the value of the ap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAP(String value) {
        this.ap = value;
    }

    /**
     * Gets the value of the sd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSD() {
        return sd;
    }

    /**
     * Sets the value of the sd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSD(String value) {
        this.sd = value;
    }

    /**
     * Gets the value of the msglst property.
     * 
     * @return
     *     possible object is
     *     {@link MSGLST }
     *     
     */
    public MSGLST getMSGLST() {
        return msglst;
    }

    /**
     * Sets the value of the msglst property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSGLST }
     *     
     */
    public void setMSGLST(MSGLST value) {
        this.msglst = value;
    }

    /**
     * Gets the value of the qrylst property.
     * 
     * @return
     *     possible object is
     *     {@link QRYLST }
     *     
     */
    public QRYLST getQRYLST() {
        return qrylst;
    }

    /**
     * Sets the value of the qrylst property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRYLST }
     *     
     */
    public void setQRYLST(QRYLST value) {
        this.qrylst = value;
    }

}
