//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:56:15 AM CET 
//


package no.ssb.linkmobility.jaxb.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qry"
})
@XmlRootElement(name = "QRYLST")
public class QRYLST {

    @XmlElement(name = "QRY", required = true)
    protected List<QRY> qry;

    /**
     * Gets the value of the qry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQRY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QRY }
     * 
     * 
     */
    public List<QRY> getQRY() {
        if (qry == null) {
            qry = new ArrayList<QRY>();
        }
        return this.qry;
    }

}
