//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:56:15 AM CET 
//


package no.ssb.linkmobility.jaxb.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logon",
    "reason",
    "msglst",
    "qrylst"
})
@XmlRootElement(name = "SESSION")
public class SESSION {

    @XmlElement(name = "LOGON", required = true)
    protected String logon;
    @XmlElement(name = "REASON", required = true)
    protected String reason;
    @XmlElement(name = "MSGLST")
    protected MSGLST msglst;
    @XmlElement(name = "QRYLST")
    protected QRYLST qrylst;

    /**
     * Gets the value of the logon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOGON() {
        return logon;
    }

    /**
     * Sets the value of the logon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOGON(String value) {
        this.logon = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREASON() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREASON(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the msglst property.
     * 
     * @return
     *     possible object is
     *     {@link MSGLST }
     *     
     */
    public MSGLST getMSGLST() {
        return msglst;
    }

    /**
     * Sets the value of the msglst property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSGLST }
     *     
     */
    public void setMSGLST(MSGLST value) {
        this.msglst = value;
    }

    /**
     * Gets the value of the qrylst property.
     * 
     * @return
     *     possible object is
     *     {@link QRYLST }
     *     
     */
    public QRYLST getQRYLST() {
        return qrylst;
    }

    /**
     * Sets the value of the qrylst property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRYLST }
     *     
     */
    public void setQRYLST(QRYLST value) {
        this.qrylst = value;
    }

}
